config/routes.rb
Rails.application.routes.draw do
  root    'standard_pages#home'
  get     '/about',   to: 'standard_pages#about'
  get     '/contact', to: 'standard_pages#contact'
  get     '/new',     to: 'standard_pages#new'
  get     '/signup',  to: 'users#new'
  post    '/signup',  to: 'users#create'
  get     '/login',   to: 'sessions#new'
  post    '/login',   to: 'sessions#create'
  delete  '/logout',  to: 'sessions#destroy'
  resources :users
  resources :ifthen_rules, only: %i[create destroy]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :ifthen_rules, dependent: :destroy
  attr_accessor :remember_token
  before_save { email.downcase! }
  # before_save { self.email = email.downcase }
  # self.email = self.email.downcase 右式のselfは省略可能/左式は省略できない
  validates :name,  presence: true, length: { maximum: 50 }
  # validates(:name, presence: true) ()は省略可能
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  # has_secure_passwordは、オブジェクト生成時に存在性を検証
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # 渡された文字列のハッシュ値を返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返す
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # 永続セッションのためにユーザーをDBに記憶
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
    # remember_token（User.new_tokenで生成された値）
    # remember_digest（remember_tokenをUser.digestでハッシュ化した値）
  end

  # 渡されたトークンがダイジェストと一致したらtrue
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # ユーザーのログイン情報を破棄
  def forget
    update_attribute(:remember_digest, nil)
  end

  # 試作feedの定義（今の所必要ないが一応残す）
  # def feed
  #   IfthenRule.where("user_id = ?", id)
  #   ↑は、ifthen_rulesと本質的に同等
  # end

  def self.search(search)
    if search
      where(['name LIKE ?', "%#{search}%"])
    else
      all
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user,              only: %i[show edit update destroy correct_user allowed_user_destory]
  before_action :logged_in_user,        only: %i[index edit update destroy]
  before_action :correct_user,          only: %i[edit update]
  before_action :allowed_user_destory,  only: :destroy

  def index
    @users = User.paginate(page: params[:page]).search(params[:search])
  end

  def show
    @ifthen_rules = @user.ifthen_rules.paginate(page: params[:page], per_page: 15).search(params[:search])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the ifthen App!"
      redirect_to @user
      # ↑は、redirect_to user_url(@user) と等価
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    if current_user.admin?
      @user.destroy
      flash[:success] = "User deleted"
      redirect_to users_url
    elsif current_user?(@user)
      @user.destroy
      flash[:success] = "Unsubscribed if-thenApp"
      redirect_to root_url
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
      # ↑の戻り値は、許可された属性のみが含まれたparamsのハッシュ (:user属性がない場合はエラー)。
    end

    # before_action

    def set_user
      @user = User.find(params[:id])
    end

    # 正しいユーザーかどうか確認
    def correct_user
      redirect_to(root_url) unless current_user?(@user)
    end

    # destoryアクションが許可されたユーザーかどうか確認
    def allowed_user_destory
      redirect_to(root_url) unless current_user.admin? || current_user?(@user)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user, url: yield(:path)) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation, "Confirmation" %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>
<% provide(:path, user_path) %>
<% provide(:button_text, 'Save changes') %>
<h1>Update your profile</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<% provide(:path,  users_path) %>
<h1>All users</h1>

<!-- 検索機能 -->
<%= render 'shared/search' %>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:path, signup_path) %>
<% provide(:button_text, 'Create my account') %>
<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<% provide(:path,  user_path) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1><%= @user.name %></h1>
    </section>
  </aside>
  <div class="col-md-8">
    <% if @user.ifthen_rules.any? %>
      <h3>If-Then Rules (<%= @user.ifthen_rules.count %>)</h3>

      <!-- 検索機能 -->
      <%= render 'shared/search' %>

      <ol class="ifthen_rules">
        <%= render @ifthen_rules %>
      </ol>
      <%= will_paginate @ifthen_rules %>
    <% end %>
  </div>
</div>